"""stylometry — Burrows's Delta against a human function-word reference.

Reported, never scored, and read in the opposite direction from the obvious one.

The stylometry literature is clear that function-word frequencies separate human
writing from LLM writing, and one paper reports 99.8% accuracy from function-word
unigrams and part-of-speech bigrams. The obvious way to use that in a linter is to
measure a document's distance from a human reference profile and flag the distant
ones. Measured on this repo's corpus, that is backwards. Delta from the human
centroid runs 0.769 on average for the human class and 0.690 for the modern-AI
class, which makes the rank statistic 0.188 rather than 0.812: model output sits
CLOSER to the human average than human writing does.

The reason is not subtle once seen. A reference profile built from thirty-odd
authors is the centroid of thirty-odd idiosyncrasies, and an instruction-tuned
model writes something very like that centroid, because averaging the population
is what the training objective rewards. Any individual writer departs from it.
So a low delta means the function-word profile has no fingerprint on it, which is
the condition model output is in and which a distinctive writer is never in.

Read in the inverted direction it separates at 0.812, which is real and still
well below the floor score's own 0.938, so it stays out of the score. It also runs
0.737 on the ESL/formal human subset, between the AI classes and the rest of the
human class, which is a second and sufficient reason never to score it.

Where it does earn its place is as a direction indicator across a rewrite. The
twenty paired files in `ai_modern_rewritten/` move from 0.690 to 0.739 and end
closer to the human median in 16 of 20 cases. That is the effect the rewrite
procedure is supposed to have, and this is the only place in the repo where it is
visible as a number. The linter reports the value with the human range beside it,
and `--baseline` reports the movement. Nothing here contributes to the score.

The profile is generated by `eval/build_profile.py` and committed as
`human_reference_profile.json`. Full argument and the measurements:
`references/competitive-landscape.md`.
"""
from __future__ import annotations

import json
import os
import re
from collections import Counter

_PROFILE_PATH = os.path.join(os.path.dirname(os.path.dirname(
    os.path.abspath(__file__))), "human_reference_profile.json")

_WORD_RE = re.compile(r"[a-z][a-z'’-]*")

_CACHE: dict = {}


def load_profile(path: str | None = None) -> dict | None:
    """Load and cache the reference profile. Returns None if it is unusable.

    The linter must keep working with the file missing or malformed, because the
    profile is a diagnostic and a diagnostic is never allowed to break a lint.
    """
    key = path or _PROFILE_PATH
    if key in _CACHE:
        return _CACHE[key]
    prof = None
    try:
        with open(key, encoding="utf-8") as fh:
            raw = json.load(fh)
        feats = raw.get("features")
        mean = raw.get("mean")
        stdev = raw.get("stdev")
        if (isinstance(feats, list) and isinstance(mean, list)
                and isinstance(stdev, list)
                and len(feats) == len(mean) == len(stdev) and feats
                and all(isinstance(f, str) for f in feats)
                and all(isinstance(v, (int, float)) for v in mean)
                and all(isinstance(v, (int, float)) and v > 0 for v in stdev)):
            prof = raw
    except (OSError, ValueError, TypeError):
        prof = None
    _CACHE[key] = prof
    return prof


def delta(prose_text: str, profile: dict | None = None) -> float | None:
    """Mean absolute z-score of this document's function-word frequencies.

    Returns None when there is no usable profile or the document is too short for
    the frequency estimates to mean anything.
    """
    prof = profile if profile is not None else load_profile()
    if not prof:
        return None
    words = _WORD_RE.findall(prose_text.lower())
    if len(words) < int(prof.get("min_words") or 80):
        return None
    n = len(words)
    counts = Counter(words)
    feats = prof["features"]
    mean = prof["mean"]
    stdev = prof["stdev"]
    total = 0.0
    for i, f in enumerate(feats):
        # Floor the divisor. load_profile() rejects a zero stdev, but delta() also
        # takes a caller-supplied profile (the eval harness and the tests pass one
        # directly), and a feature with no variance in the reference set would
        # otherwise divide by zero rather than contributing nothing.
        total += abs((counts[f] / n - mean[i]) / (stdev[i] or 1e-9))
    return total / len(feats)


def report_stylometry(prose_text: str, report: dict, profile: dict | None = None) -> None:
    """Add the delta and the human range to the metrics. Never adds a hit."""
    prof = profile if profile is not None else load_profile()
    if not prof:
        return
    d = delta(prose_text, prof)
    if d is None:
        return
    report["stylometric_delta"] = round(d, 3)
    for key in ("human_delta_median", "human_delta_min", "human_delta_max"):
        v = prof.get(key)
        report[key] = round(v, 3) if isinstance(v, (int, float)) else v
    lo = prof.get("human_delta_min")
    # "Below every human document in the reference set" is the only claim this
    # metric supports on its own, and even that is a prompt to look rather than a
    # verdict. Anything inside the range says nothing.
    if isinstance(lo, (int, float)) and d < lo:
        report["stylometric_flat"] = True


__all__ = [
    "load_profile",
    "delta",
    "report_stylometry",
]
